import { describe, expect, it, vi } from "vitest";
import { generateWithOllama } from "../src/ollama-adapter.js";
import { runWorkerOnce } from "../src/worker.js";

describe("Ollama adapter", () => {
  it("sends a bounded non-streaming request and returns the generated text", async () => {
    const fetcher = vi.fn(async (input: URL | RequestInfo, init?: RequestInit) => {
      const url = String(input);
      const body = JSON.parse(String(init?.body));
      expect(body).toMatchObject({ model: "llama3.2", prompt: "hello", stream: false });
      return new Response(JSON.stringify({ response: "hello human" }), { status: 200 });
    });
    const output = await generateWithOllama({ baseUrl: "http://127.0.0.1:11434", model: "llama3.2", prompt: "hello", fetcher });
    expect(output).toBe("hello human");
  });
});

describe("worker cycle", () => {
  it("claims one job, runs the adapter and completes the same lease", async () => {
    const requests: Array<{ url: string; init?: RequestInit }> = [];
    const fetcher = vi.fn(async (url: string, init?: RequestInit) => {
      requests.push({ url, init });
      if (url.endsWith("/api/worker/claim")) {
        return new Response(JSON.stringify({
          leaseToken: "lease-token-with-enough-entropy",
          job: { id: "job-1", prompt: "say hello", serviceId: "text.openai.sol", requirements: ["text"] },
          serviceIds: ["text.openai.sol"],
          attempt: { id: "11111111-1111-4111-8111-111111111111" }
        }), { status: 200, headers: { "content-type": "application/json" } });
      }
      return new Response(JSON.stringify({ state: "succeeded" }), { status: 200, headers: { "content-type": "application/json" } });
    });

    const outcome = await runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.openai.sol"],
      fetcher,
      execute: async (job) => `generated by ${job.serviceId}: ${job.prompt}`
    });

    expect(outcome).toBe("completed");
    expect(requests).toHaveLength(2);
    expect(JSON.parse(String(requests[0]!.init?.body))).toEqual({ capabilities: ["text.openai.sol"], acceptPublicRequests: false });
    expect(JSON.parse(String(requests[1]!.init?.body))).toEqual({
      leaseToken: "lease-token-with-enough-entropy",
      output: "generated by text.openai.sol: say hello"
    });
  });

  it("rejects a lease whose selected services do not cover every declared requirement", async () => {
    const fetcher = vi.fn(async () => new Response(JSON.stringify({
      leaseToken: "lease-token-with-enough-entropy",
      job: { id: "job-incomplete", prompt: "write copy and create an image", serviceId: "text.openai.sol", requirements: ["text", "image"] },
      serviceIds: ["text.openai.sol"],
      attempt: { id: "44444444-4444-4444-8444-444444444444" }
    }), { status: 200, headers: { "content-type": "application/json" } }));

    await expect(runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.openai.sol", "image.openai.gpt-image-2"],
      fetcher,
      execute: async () => "should not run"
    })).rejects.toThrow("invalid lease");
  });

  it("rejects coordinator-selected services that the worker did not advertise", async () => {
    const fetcher = vi.fn(async () => new Response(JSON.stringify({
      leaseToken: "lease-token-with-enough-entropy",
      job: { id: "job-unapproved", prompt: "create an image", serviceId: "image.openai.gpt-image-2", requirements: ["image"] },
      serviceIds: ["image.openai.gpt-image-2"],
      attempt: { id: "55555555-5555-4555-8555-555555555555" }
    }), { status: 200, headers: { "content-type": "application/json" } }));

    await expect(runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.ollama"],
      fetcher,
      execute: async () => "should not run"
    })).rejects.toThrow("unapproved service");
  });

  it("accepts coordinator-selected services from the top-level claim response", async () => {
    const execute = vi.fn(async (job: { serviceIds?: string[] }) => JSON.stringify({ selected: job.serviceIds }));
    const fetcher = vi.fn(async (url: string, init?: RequestInit) => {
      if (url.endsWith("/api/worker/claim")) {
        return new Response(JSON.stringify({
          leaseToken: "lease-token-with-enough-entropy",
          job: { id: "job-top-level", prompt: "write copy and create an image", serviceId: "text.openai.sol" },
          serviceIds: ["text.openai.sol", "image.openai.gpt-image-2"],
          attempt: { id: "33333333-3333-4333-8333-333333333333" }
        }), { status: 200, headers: { "content-type": "application/json" } });
      }
      expect(JSON.parse(String(init?.body)).output).toBe(JSON.stringify({ selected: ["text.openai.sol", "image.openai.gpt-image-2"] }));
      return new Response(JSON.stringify({ state: "succeeded" }), { status: 200 });
    });

    await expect(runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.openai.sol", "image.openai.gpt-image-2"],
      fetcher,
      execute
    })).resolves.toBe("completed");
  });

  it("accepts a combined serviceIds lease and completes it with composite executor output", async () => {
    const execute = vi.fn(async (job: { serviceId: string; serviceIds?: string[] }) => JSON.stringify({ selected: job.serviceIds }));
    const fetcher = vi.fn(async (url: string, init?: RequestInit) => {
      if (url.endsWith("/api/worker/claim")) {
        return new Response(JSON.stringify({
          leaseToken: "lease-token-with-enough-entropy",
          job: { id: "job-many", prompt: "compare", serviceIds: ["text.openai.sol", "text.anthropic.fable"] },
          attempt: { id: "22222222-2222-4222-8222-222222222222" }
        }), { status: 200, headers: { "content-type": "application/json" } });
      }
      expect(JSON.parse(String(init?.body)).output).toBe(JSON.stringify({ selected: ["text.openai.sol", "text.anthropic.fable"] }));
      return new Response(JSON.stringify({ state: "succeeded" }), { status: 200 });
    });

    await expect(runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.openai.sol", "text.anthropic.fable"],
      fetcher,
      execute
    })).resolves.toBe("completed");
    expect(execute).toHaveBeenCalledWith(expect.objectContaining({
      serviceId: "text.openai.sol",
      serviceIds: ["text.openai.sol", "text.anthropic.fable"]
    }));
  });
});
